spring:
  data:
    mongodb:
      host: '${MONGO_HOST:localhost}'
      port: 27017
      database: admin
      username: root
      password: hello
  cloud:
    loadbalancer:
      ribbon:
        enable: false

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
location-client:
  base-url: http://productlocations.free.beeceptor.com
  sub-url: /default
---
spring:
  profiles: dev
location-client:
  sub-url: /dev
